sudo: required

branches:
  only:
  - master

cache: yarn

language: node_js
node_js:
  - "6"

before_install:
  - rvm install ruby-2.3.3
  - rvm use 2.3.3
  - gem install kontena-cli
  - kontena version

install: true

services:
  - docker

jobs:
  include:
  - stage: build container
    node_js: "6"
    script: test/build.sh
  - stage: test
    env: VISUAL=chrome59
    node_js: "6"
    script: test/visual.sh
  - stage: deploy
    node_js: "6"
    script: test/deploy-kontena.sh

  #  - stage: test
  #    env: VISUAL=edge15
  #    node_js: "6"
  #    script: test/visual.sh
  #  - stage: test
  #    env: VISUAL=ie11
  #    node_js: "6"
  #    script: test/visual.sh
  #  - stage: test
  #    env: VISUAL=safari10
  #    node_js: "6"
  #    script: test/visual.sh
