stack: coodari/digiprod
version: 0.5.0
description: Oulu Digitransit Project

variables:
  front_service_version:
    type: string
    from:
      vault: FRONT_SERVICE_VERSION

services:
  lb-proxy:
    image: kontena/lb:latest
    ports:
      - 443:443
      - 80:80
    deploy:
      strategy: daemon
    secrets:
      - secret: SSL_LOAD_BALANCER_CERT_BUNDLE
        name: SSL_CERTS
        type: env

  digidev:
    image: "quay.io/codeverde/digitransit-ui:${front_service_version}"
    environment:
      - CONFIG=oulu20
      - KONTENA_LB_MODE=http
      - KONTENA_LB_BALANCE=roundrobin
      - KONTENA_LB_INTERNAL_PORT=8080
      - KONTENA_LB_CUSTOM_SETTINGS=redirect scheme https code 301 if !{ ssl_fc }
    deploy:
      strategy: daemon
    links:
      - lb-proxy
    secrets:
      - secret: FRONT_SERVICE_DOMAIN
        name: KONTENA_LB_VIRTUAL_HOSTS
        type: env
      - secret: PIWIK_ADDRESS
        name: PIWIK_ADDRESS
        type: env
      - secret: PIWIK_ID
        name: PIWIK_ID
        type: env
