stack: coodari/digiprod
version: 0.8.0
description: Oulu Digitransit Project

variables:
  front_service_version:
    type: string
    from:
      vault: FRONT_SERVICE_VERSION

services:
  lb-proxy:
    image: kontena/lb:latest
    ports:
      - 443:443
      - 80:80
    deploy:
      strategy: daemon
    certificates:
      - subject: pilot1.its-oulu-pilots.fi
        type: env
        name: SSL_CERTS
      - subject: stats.pilot1.its-oulu-pilots.fi
        type: env
        name: SSL_CERTS

  digidev:
    image: "quay.io/codeverde/digitransit-ui:${front_service_version}"
    environment:
      - CONFIG=oulu20
      - KONTENA_LB_MODE=http
      - KONTENA_LB_BALANCE=roundrobin
      - KONTENA_LB_INTERNAL_PORT=8080
      - KONTENA_LB_CUSTOM_SETTINGS=redirect scheme https code 301 if !{ ssl_fc }
    deploy:
      strategy: daemon
    links:
      - lb-proxy
    secrets:
      - secret: FRONT_SERVICE_DOMAIN
        name: KONTENA_LB_VIRTUAL_HOSTS
        type: env
      - secret: PIWIK_ADDRESS
        name: PIWIK_ADDRESS
        type: env
      - secret: PIWIK_ID
        name: PIWIK_ID
        type: env

  piwik-app4:
    image: bitnami/piwik:3.0.4-r5
    stateful: true
    environment:
      - KONTENA_LB_MODE=http
      - KONTENA_LB_BALANCE=roundrobin
      - KONTENA_LB_INTERNAL_PORT=80
      - KONTENA_LB_CUSTOM_SETTINGS=redirect scheme https code 301 if !{ ssl_fc }
      - PIWIK_WEBSITE_NAME=Digitransit
      - PIWIK_WEBSITE_HOST=https://pilot1.its-oulu-pilots.fi
      - MARIADB_USER=root
      - MARIADB_HOST=piwik-db4
    links:
      - lb-proxy
    secrets:
      - secret: PIWIK_SERVICE_DOMAIN
        name: KONTENA_LB_VIRTUAL_HOSTS
        type: env
      - secret: PIWIK_USER_PASSWORD
        name: PIWIK_PASSWORD
        type: env
      - secret: PIWIK_DB_PASSWORD
        name: MARIADB_PASSWORD
        type: env

  piwik-db4:
    image: mariadb:10.3.1
    stateful: true
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    secrets:
      - secret: PIWIK_DB_PASSWORD
        name: MYSQL_ROOT_PASSWORD
        type: env
