export default [
  {
    venueId: 1,
    name: 'Oulun Kaupungin Teatteri',
    geometry: [
      65.0145578,
      25.4602261,
    ],
    events: [
      {
        id: 11,
        name: 'Useita tilaisuuksia',
        description: 'Tervetuloa Oulun Kaupungin Teatteriin! Ohjelmistossa tänä syksynä:<br />-Rautatie Ilosia aikoja<br />-Mielensäpahoittaja<br />-Saituri ja Lasse-Maijan etsivätoimisto<br />...ja paljon muuta<br /><br />Lue lisää syksyn ohjelmistosta lisätietojen linkeistä.',
        infoLink: 'http://teatteri.ouka.fi/ohjelmisto/nyt-ohjelmistossa',
        extraInfo: [
          {
            linkText: 'Ohjelmakalenteri ja lipunvaraus',
            url: 'http://teatteri.ouka.fi/esityskalenteri',
          },
        ],
        startDate: '2017-09-02',
        endDate: '2017-12-31',
        tags: ['theatre'],
      },
    ],
  },
  {
    venueId: 2,
    name: 'Oulu Sinfonia',
    geometry: [
      65.0033996,
      25.4785274,
    ],
    events: [
      {
        id: 21,
        name: 'Beethoven konsertti 1',
        description: 'Unohtumatonta musiikkia, vaikuttavaa virtuositeettia ja sydämeenkäyviä tulkintoja on luvassa Brautigam plays Beethoven -minifestivaalilla, jossa aikamme ylistetyimpiin pianisteihin lukeutuva Ronald Brautigam ja Oulu Sinfonia esittävät säveltäjän kuusi pianokonserttoa peräkkäisinä päivinä Madetojan salissa.<br /><br />Osa Brautigam plays Beethoven -minifestivaalia.',
        infoLink: 'http://www.oulusinfonia.fi/konserttipohja/beethoven-konsertti-1.html',
        extraInfo: [
          {
            linkText: 'Ohjelmakalenteri ja lipunvaraus',
            url: 'http://www.oulusinfonia.fi/konsertit.html',
          },
        ],
        startDate: '2017-10-05',
        endDate: '2017-10-05',
        startTime: '19:00',
        endTime: '20:35',
        tags: ['music'],
      },
      {
        id: 22,
        name: 'Beethoven konsertti 1',
        description: 'Unohtumatonta musiikkia, vaikuttavaa virtuositeettia ja sydämeenkäyviä tulkintoja on luvassa Brautigam plays Beethoven -minifestivaalilla, jossa aikamme ylistetyimpiin pianisteihin lukeutuva Ronald Brautigam ja Oulu Sinfonia esittävät säveltäjän kuusi pianokonserttoa peräkkäisinä päivinä Madetojan salissa.<br /><br />Osa Brautigam plays Beethoven -minifestivaalia.',
        infoLink: 'http://www.oulusinfonia.fi/konserttipohja/beethoven-konsertti-2.html',
        extraInfo: [
          {
            linkText: 'Ohjelmakalenteri ja lipunvaraus',
            url: 'http://www.oulusinfonia.fi/konsertit.html',
          },
        ],
        startDate: '2017-10-06',
        endDate: '2017-10-06',
        startTime: '18:00',
        endTime: '19:30',
        tags: ['music'],
      },
      {
        id: 23,
        name: 'Beethoven konsertti 3',
        description: 'Unohtumatonta musiikkia, vaikuttavaa virtuositeettia ja sydämeenkäyviä tulkintoja on luvassa Brautigam plays Beethoven -minifestivaalilla, jossa aikamme ylistetyimpiin pianisteihin lukeutuva Ronald Brautigam ja Oulu Sinfonia esittävät säveltäjän kuusi pianokonserttoa peräkkäisinä päivinä Madetojan salissa.<br /><br />Osa Brautigam plays Beethoven -minifestivaalia.',
        infoLink: 'http://www.oulusinfonia.fi/konserttipohja/beethoven-konsertti-3.html',
        extraInfo: [
          {
            linkText: 'Ohjelmakalenteri ja lipunvaraus',
            url: 'http://www.oulusinfonia.fi/konsertit.html',
          },
        ],
        startDate: '2017-10-07',
        endDate: '2017-10-07',
        startTime: '15:00',
        endTime: '16:40',
        tags: ['music'],
      },
      {
        id: 24,
        name: 'Tapio – perhekonsertti',
        description: 'Lastenkonsertti Tapio vie yleisön kiehtovalle matkalle suomalaiseen mytologiaan ja kansantarustoon. Tarinan runkona toimivat lasten suosikeiksi nousseet kappaleet Jussi Rasinkankaan kokoelmasta ”Toiseen maailmaan”. Tomi Valon ottamat upeat luontokuvat ja Annamari Kessin kekseliäs koreografia tukevat tarinaa visuaalisesti.<br /><br />Tapio on osoitus oululaisen musiikkikasvatuksen mahtivoimasta ja musiikkitoimijoiden yhteistyöstä, jonka hedelmistä pääsevät nauttimaan kaikki alueen asukkaat. Perhekonsertti Tapio on osa Suomen itsenäisyyden satavuotisjuhlavuoden ohjelmaa. Konsertti on suunnattu erityisesti 5–12 -vuotiaille lapsille ja heidän vanhemmilleen.',
        infoLink: 'http://www.oulusinfonia.fi/konserttipohja/tapio-perhekonsertti.html',
        extraInfo: [
          {
            linkText: 'Ohjelmakalenteri ja lipunvaraus',
            url: 'http://www.oulusinfonia.fi/konsertit.html',
          },
        ],
        startDate: '2017-10-12',
        endDate: '2017-10-12',
        startTime: '18:00',
        endTime: '19:00',
        tags: ['music'],
      },
      {
        id: 25,
        name: 'WE COME IN PEACE - Orchestral Science Fiction Music',
        description: 'Kiinnitä turvavyö ja valmistaudu matkaamaan valon nopeudella läpi syksyn suosituimman kulttuurikokemuksen. WE COME IN PEACE etsii kaukaisilta planeetoilta älyllistä elämää ja vie eeppisille sotatantereille sekä taisteluihin galaktisten hirviöiden keskelle. Konsertin isäntänä toimii mediapersoona ja scifi-rakastaja Orvar Säfström ja solistina itseoikeutetusti harvinaislaatuisen ja aavemaisen thereminin taituri Kristoffer Eng.<br /><br />Läpileikkaus scifi-maailmaan kattaa aikakaudet 50-luvulta tähän päivään sisältäen musiikkia mm. Star Warsista, Star Trekistä, Avataresta, Halosta ja Taisteluplaneetta Galacticasta. Tämä kokemus on omistettu kaikille, jotka ovat koskaan suunnanneet kaihoisan katseen kaukaisille tähtitaivaille.',
        infoLink: 'http://www.oulusinfonia.fi/konserttipohja/we-come-in-peace-orchestral-science-fiction-music.html',
        extraInfo: [
          {
            linkText: 'Ohjelmakalenteri ja lipunvaraus',
            url: 'http://www.oulusinfonia.fi/konsertit.html',
          },
        ],
        startDate: '2017-11-15',
        endDate: '2017-11-15',
        startTime: '19:00',
        endTime: '21:00',
        tags: ['music'],
      },
      {
        id: 26,
        name: 'WE COME IN PEACE - Orchestral Science Fiction Music',
        description: 'Kiinnitä turvavyö ja valmistaudu matkaamaan valon nopeudella läpi syksyn suosituimman kulttuurikokemuksen. WE COME IN PEACE etsii kaukaisilta planeetoilta älyllistä elämää ja vie eeppisille sotatantereille sekä taisteluihin galaktisten hirviöiden keskelle. Konsertin isäntänä toimii mediapersoona ja scifi-rakastaja Orvar Säfström ja solistina itseoikeutetusti harvinaislaatuisen ja aavemaisen thereminin taituri Kristoffer Eng.<br /><br />Läpileikkaus scifi-maailmaan kattaa aikakaudet 50-luvulta tähän päivään sisältäen musiikkia mm. Star Warsista, Star Trekistä, Avataresta, Halosta ja Taisteluplaneetta Galacticasta. Tämä kokemus on omistettu kaikille, jotka ovat koskaan suunnanneet kaihoisan katseen kaukaisille tähtitaivaille.',
        infoLink: 'http://www.oulusinfonia.fi/konserttipohja/we-come-in-peace-orchestral-science-fiction-music-2.html',
        extraInfo: [
          {
            linkText: 'Ohjelmakalenteri ja lipunvaraus',
            url: 'http://www.oulusinfonia.fi/konsertit.html',
          },
        ],
        startDate: '2017-11-16',
        endDate: '2017-11-16',
        startTime: '19:00',
        endTime: '21:00',
        tags: ['music'],
      },
      {
        id: 27,
        name: 'Suomalaisen elokuvan 100 vuotta',
        description: 'Aivan kuten musiikki, myös kotimainen elokuva on käsitellyt maamme historian käänteitä ja ilmentänyt kansalaisten tuntoja monin tavoin. Itsenäisyyspäivän konsertissa nautitaan suomalaisen elokuvan valittuja paloja herkullisten musiikkiesitysten ja projisointien kautta.<br /><br />Sadan vuoden aikajänteeseen mahtuu musiikkia iskelmän kulta-ajalta taidemusiikin massiivisempiin numeroihin unohtamatta kaikille tuttuja koskettavia klassikoita. Konsertti toteutetaan yhteistyössä Oulun Elokuvakeskus ry:n kanssa.',
        infoLink: 'http://www.oulusinfonia.fi/konserttipohja/suomalaisen-elokuvan-100-vuotta.html',
        extraInfo: [
          {
            linkText: 'Ohjelmakalenteri ja lipunvaraus',
            url: 'http://www.oulusinfonia.fi/konsertit.html',
          },
        ],
        startDate: '2017-12-06',
        endDate: '2017-12-06',
        startTime: '13:00',
        endTime: '14:00',
        tags: ['music'],
      },
      {
        id: 28,
        name: 'Joulukonsertti Leifin kanssa',
        description: 'Oulu Sinfonian juhlavuosi päättyy itsensä Leif Segerstamin harppukonserton kantaesitykseen joulun tunnelmaa pulppuilevassa konsertissa.<br /><br />Nykymusiikin vastapainona kuullaan vanhaan ranskalaiseen joululauluun perustuva joulupastoraali sekä perinteisiä, tuttuja joululauluja Madetojan musiikkilukion lippulaivana toimivan tyttökuoron ja Oulu Sinfonian esittämänä.',
        infoLink: 'http://www.oulusinfonia.fi/konserttipohja/joulukonsertti-leifin-kanssa.html',
        extraInfo: [
          {
            linkText: 'Ohjelmakalenteri ja lipunvaraus',
            url: 'http://www.oulusinfonia.fi/konsertit.html',
          },
        ],
        startDate: '2017-12-14',
        endDate: '2017-12-14',
        startTime: '19:00',
        endTime: '20:50',
        tags: ['music'],
      },
    ],
  },
  {
    venueId: 3,
    name: 'Pikkujoulu Piknik',
    geometry: [
      65.007995,
      25.4989617,
    ],
    events: [
      {
        id: 31,
        name: 'Pikkujoulu Piknik Ouluhallissa',
        description: 'Kahdeksatta kertaa järjestettävä Pohjois-Suomen suurin pikkujoulutapahtuma Pikkujoulu Piknik esittää jälleen kerran ainutlaatuisen ja huikean ohjelman.<br /><br />Esiintyjinä LAURI TÄHKÄ, DINGO huippuvuosien alkuperäiskokoonpanolla, ERIN sekä ensimmäistä kertaansa viihdemusiikin pariin asteleva oululainen PETRUS SCHRODERUS ORKESTEREINEEN.',
        infoLink: 'http://www.piknik.fi/pikkujoulu-piknik-2017/',
        startDate: '2017-11-25',
        endDate: '2017-11-25',
        tags: ['festival'],
      },
    ],
  },
  {
    venueId: 4,
    name: 'Kulttuuritalo Valve',
    geometry: [
      65.0141775,
      25.4681372,
    ],
    events: [
      {
        id: 41,
        name: 'Oulun kansainvälinen lasten- ja nuortenelokuvien festivaali',
        description: 'Oulun kansainvälinen lasten- ja nuortenelokuvien festivaali on Pohjoismaiden vanhin lastenelokuvien festivaali, joka kerää vuosittain n. 30 000 kävijää. Viikon kestävän tapahtuman aikana Oulu täyttyy sadoista tarinoista, kun festivaali levittäytyy valkokankaille, seminaarisaleihin ja näyttelytiloihin.<br /><br />Marraskuisella festivaalilla esitetään aamusta iltaan taiteellisesti korkeatasoisia lasten- ja nuortenelokuvia eri puolilta maailmaa. Pienille lapsille suunnatut elokuvat joko mikrofonitulkataan tai tekstitetään suomeksi.',
        infoLink: 'http://www.oulunelokuvakeskus.fi/lef/fi/etusivu',
        startDate: '2017-11-13',
        endDate: '2017-11-19',
        tags: ['festival', 'children'],
      },
    ],
  },
  {
    venueId: 5,
    name: 'Oulun pääkirjasto',
    geometry: [
      65.0154421,
      25.4634084,
    ],
    events: [
      {
        id: 51,
        name: 'Hobitti 80 vuotta!',
        description: 'Hobitti 80 vuotta! J. R. R. Tolkienin fantasiaromaani Hobitti ilmestyi ensimmäisen kerran 21.9.1937. Hobitin 80-vuotissyntymäpäivän johdosta Oulun pääkirjaston lasten ja nuorten osastolla järjestetään Hobitti-ilta.',
        infoLink: 'http://bit.ly/hobitti2017',
        startDate: '2017-09-21',
        endDate: '2017-09-21',
        startTime: '17:00',
        endTime: '19:30',
        tags: ['children'],
      },
    ],
  },
  {
    venueId: 6,
    name: 'Oulun kauppatori',
    geometry: [
      65.0135309,
      25.4621188,
    ],
    events: [
      {
        id: 61,
        name: 'Vuoden 2017 Lumo-valofestivaali',
        description: 'Lumo-valofestivaalilla on koettavana lukuisia teoksia ja yhteisöllisiä valoteemaisia tapahtumia.',
        infoLink: 'https://www.ouka.fi/lumo',
        startDate: '2017-11-17',
        endDate: '2017-12-03',
        tags: ['festival'],
      },
    ],
  },
  {
    venueId: 7,
    name: 'Oulun Musiikkikeskus',
    geometry: [
      65.0035723,
      25.4791283,
    ],
    events: [
      {
        id: 71,
        name: 'Uuden musiikin lokakuu',
        description: 'Tervetuloa Uuden Musiikin Lokakuu -festivaalille, joka on tänä vuonna nykymusiikin superviikonloppu! Suomen itsenäisyyden 100-vuotisjuhlan kunniaksi ohjelmistossa on paljon suomalaista musiikkia.',
        infoLink: 'http://lokakuu.fi/',
        startDate: '2017-09-28',
        endDate: '2017-09-30',
        startTime: '17:00',
        endTime: '19:00',
        tags: ['festival', 'music'],
      },
    ],
  },
  {
    venueId: 8,
    name: 'Raksila 2 - harjoitusjäähalli',
    geometry: [
      65.0080934,
      25.4935349,
    ],
    events: [
      {
        id: 81,
        name: 'Jääkiekon Naisten Liiga',
        description: 'Kärpät (Oulu) - HPK (Hämeenlinna).',
        infoLink: 'http://www.oulunkarpat46.fi/naiset',
        startDate: '2017-09-30',
        endDate: '2017-09-30',
        tags: ['sport'],
      },
    ],
  },
  {
    venueId: 9,
    name: 'Oulun Energia Areena',
    geometry: [
      65.0082171,
      25.4926694,
    ],
    events: [
      {
        id: 91,
        name: 'Jääkiekon SM-Liiga',
        description: 'Kärpät (Oulu) - HPK (Hämeenlinna).',
        infoLink: 'http://www.oulunkarpat.fi/',
        startDate: '2017-09-09',
        endDate: '2017-09-09',
        startTime: '17:00',
        endTime: '20:00',
        tags: ['sport'],
      },
      {
        id: 92,
        name: 'Jääkiekon SM-Liiga',
        description: 'Kärpät (Oulu) - HPK (Hämeenlinna).',
        infoLink: 'http://www.oulunkarpat.fi/',
        startDate: '2017-09-09',
        endDate: '2017-09-09',
        startTime: '17:00',
        endTime: '20:00',
        tags: ['sport'],
      },
      {
        id: 93,
        name: 'Jääkiekon SM-Liiga',
        description: 'Kärpät (Oulu) - Sport (Vaasa).',
        infoLink: 'http://www.oulunkarpat.fi/',
        startDate: '2017-09-16',
        endDate: '2017-09-16',
        startTime: '17:00',
        endTime: '20:00',
        tags: ['sport'],
      },
      {
        id: 94,
        name: 'Jääkiekon SM-Liiga',
        description: 'Kärpät (Oulu) - JYP (Jyväskylä).',
        infoLink: 'http://www.oulunkarpat.fi/',
        startDate: '2017-10-07',
        endDate: '2017-10-07',
        startTime: '17:00',
        endTime: '20:00',
        tags: ['sport'],
      },
      {
        id: 95,
        name: 'Jääkiekon SM-Liiga',
        description: 'Kärpät (Oulu) - HIFK (Helsinki).',
        infoLink: 'http://www.oulunkarpat.fi/',
        startDate: '2017-10-18',
        endDate: '2017-10-18',
        startTime: '18:30',
        endTime: '21:30',
        tags: ['sport'],
      },
      {
        id: 96,
        name: 'Jääkiekon SM-Liiga',
        description: 'Kärpät (Oulu) - Lukko (Rauma).',
        infoLink: 'http://www.oulunkarpat.fi/',
        startDate: '2017-10-26',
        endDate: '2017-10-26',
        startTime: '18:30',
        endTime: '21:30',
        tags: ['sport'],
      },
      {
        id: 97,
        name: 'Jääkiekon SM-Liiga',
        description: 'Kärpät (Oulu) - Tappara (Tampere).',
        infoLink: 'http://www.oulunkarpat.fi/',
        startDate: '2017-11-21',
        endDate: '2017-11-21',
        startTime: '18:30',
        endTime: '21:30',
        tags: ['sport'],
      },
      {
        id: 98,
        name: 'Jääkiekon SM-Liiga',
        description: 'Kärpät (Oulu) - Jukurit (Mikkeli).',
        infoLink: 'http://www.oulunkarpat.fi/',
        startDate: '2017-11-28',
        endDate: '2017-11-28',
        startTime: '18:30',
        endTime: '21:30',
        tags: ['sport'],
      },
      {
        id: 99,
        name: 'Jääkiekon SM-Liiga',
        description: 'Kärpät (Oulu) - Ässät (Pori).',
        infoLink: 'http://www.oulunkarpat.fi/',
        startDate: '2017-12-02',
        endDate: '2018-12-02',
        startTime: '17:00',
        endTime: '20:00',
        tags: ['sport'],
      },
      {
        id: 910,
        name: 'Jääkiekon SM-Liiga',
        description: 'Kärpät (Oulu) - TPS (Turku).',
        infoLink: 'http://www.oulunkarpat.fi/',
        startDate: '2018-01-06',
        endDate: '2018-01-06',
        startTime: '17:00',
        endTime: '20:00',
        tags: ['sport'],
      },
    ],
  },
  {
    venueId: 10,
    name: 'Oulun taidemuseo',
    geometry: [
      65.0190215,
      25.4822172,
    ],
    events: [
      {
        id: 1001,
        name: 'LIITOS – Luonto uudessa tarkastelussa',
        description: 'Suomen Biotaiteen Seura ry:n ja Oulun taidemuseon tuottama kansainvälinen nykytaidenäyttely tarkentaa katseen ihmisen luontosuhteeseen ja muuttuvaan ympäristöön.',
        infoLink: 'https://www.ouka.fi/oulu/luuppi/liitos',
        extraInfo: [
          {
            linkText: 'Tämän hetken näyttelyt Oulun taidemuseossa',
            url: 'https://www.ouka.fi/oulu/luuppi/etusivu',
          },
          {
            linkText: 'Tulevat näyttelyt Oulun taidemuseossa',
            url: 'https://www.ouka.fi/oulu/luuppi/tulevat-nayttelyt',
          },
        ],
        startDate: '2017-05-11',
        endDate: '2017-11-12',
        tags: ['museum'],
      },
      {
        id: 1002,
        name: 'Näytönpaikka pohjoisessa piilaaksossa',
        description: 'Mikä sai alkunsa vuonna 1979 Oulussa? Kuka oli sotkamolainen Toivo Ruokko, sähköteekkari josta tuli hetkeksi maailman juhlituin teknologiaguru ja yritysjohtaja? Tekikö Toivo Ruokko Suomen yrityshistorian karuimman konkurssin, vai mitä Toivolle tapahtui?',
        infoLink: 'https://www.ouka.fi/naytonpaikka',
        extraInfo: [
          {
            linkText: 'Tämän hetken näyttelyt Oulun taidemuseossa',
            url: 'https://www.ouka.fi/oulu/luuppi/etusivu',
          },
          {
            linkText: 'Tulevat näyttelyt Oulun taidemuseossa',
            url: 'https://www.ouka.fi/oulu/luuppi/tulevat-nayttelyt',
          },
        ],
        startDate: '2017-12-02',
        endDate: '2019-01-06',
        tags: ['museum'],
      },
    ],
  },
  {
    venueId: 11,
    name: 'Oulun taidemuseo',
    geometry: [
      65.0189441,
      25.4809093,
    ],
    events: [
      {
        id: 1101,
        name: 'Comics Effects',
        description: 'Sarjakuva- ja kuvitustaide ovat päivittäin läsnä jokaisen suomalaisen elämässä, mutta sarjakuva on myös oma taidemuotonsa, jolla on ollut ja on vaikutusta kuvataiteeseen ja taiteen tekijöihin.<br /><br />Oulun sarjakuvakeskuksen tuottamassa moni-ilmeisessä kokonaisuudessa nähdään mm. Veikko ”Joonas” Savolaisen, JP Ahosen, Kaisa Lekan ja Harri Filpan näyttelyt.',
        infoLink: 'https://www.ouka.fi/oulu/luuppi/comics-effects',
        extraInfo: [
          {
            linkText: 'Tämän hetken näyttelyt Oulun taidemuseossa',
            url: 'https://www.ouka.fi/oulu/luuppi/etusivu',
          },
          {
            linkText: 'Tulevat näyttelyt Oulun taidemuseossa',
            url: 'https://www.ouka.fi/oulu/luuppi/tulevat-nayttelyt',
          },
        ],
        startDate: '2017-12-02',
        endDate: '2018-01-07',
        tags: ['museum'],
      },
    ],
  },
];
