export default [
  // https://www.ouka.fi/oulu/liikunta-ja-ulkoilu/kuntoilupuistot
  {
    id: 1,
    name: 'Hiironen',
    geometry: [
      64.9876016,
      25.5260095,
    ],
    description: 'Hiirosen urheilupuisto (os. Urheilupuistontie, 90250 Oulu) sijaitsee Kaukovainion kuntoradan ja Iinatinlenkin kuntoratojen yhteydessä nurmikenttien vierellä.  Fitness-puisto soveltuu eritasoisille liikkujille, myös aktiivikuntoilijoille.<br /><br />Liikuntapalvelut vastaa kuntoilupuistojen laitteista ja alueista, alueiden kunnossapidon hoitaa Teknisen Liikelaitoksen ylläpito-osasto. Ei talvikunnossapitoa.',
    infoLink: 'https://www.ouka.fi/oulu/liikunta-ja-ulkoilu/kuntoilupuistot',
    startDate: '2017-09-01',
    endDate: '2017-12-01',
  },
  {
    id: 2,
    name: 'Hollihaka',
    geometry: [
      65.007676,
      25.4526414,
    ],
    description: 'Oulun uusin ulkokuntoilupuisto löytyy Hollihaasta. Vehreässä puistoympäristössä sijaitseva ulkokuntoilupuisto on suunnattu laaja-alaisesti kaikille liikkujille.<br /><br />Liikuntapalvelut vastaa kuntoilupuistojen laitteista ja alueista, alueiden kunnossapidon hoitaa Teknisen Liikelaitoksen ylläpito-osasto. Ei talvikunnossapitoa.',
    infoLink: 'https://www.ouka.fi/oulu/liikunta-ja-ulkoilu/kuntoilupuistot',
    startDate: '2017-09-01',
    endDate: '2017-12-01',
  },
  {
    id: 3,
    name: 'Kuusisaari',
    geometry: [
      65.0215804,
      25.4610488,
    ],
    description: 'Kuusisaaren kuntoilupuisto  löytyy Raatin puoleisesta kärjestä, Kuusisaaren sisäänkäynnin tuntumasta. Kauniissa jokimaisemissa sijaitseva puisto on suunniteltu vastaamaan mahdollisimman laaja-alaisen käyttäjäryhmän tarpeisiin.<br /><br />Liikuntapalvelut vastaa kuntoilupuistojen laitteista ja alueista, alueiden kunnossapidon hoitaa Teknisen Liikelaitoksen ylläpito-osasto. Ei talvikunnossapitoa.',
    infoLink: 'https://www.ouka.fi/oulu/liikunta-ja-ulkoilu/kuntoilupuistot',
    startDate: '2017-09-01',
    endDate: '2017-12-01',
  },
  {
    id: 4,
    name: 'Tuira',
    geometry: [
      65.026858,
      25.454322,
    ],
    description: 'Tuirassa sijaitsevassa Tervaporvarin puistossa (Koskitie 8, 90500 Oulu) on laitteita kaiken ikäisille kuntoilijoille.<br /><br />Liikuntapalvelut vastaa kuntoilupuistojen laitteista ja alueista, alueiden kunnossapidon hoitaa Teknisen Liikelaitoksen ylläpito-osasto. Ei talvikunnossapitoa.',
    infoLink: 'https://www.ouka.fi/oulu/liikunta-ja-ulkoilu/kuntoilupuistot',
    startDate: '2017-09-01',
    endDate: '2017-12-01',
  },
  {
    id: 5,
    name: 'Ritaharju',
    geometry: [
      65.087695,
      25.4431523,
    ],
    description: 'Ritaharjun fitness-puisto sijaitsee kuntoratasillan kupeessa, Ritaväyläntien varressa.<br /><br />Liikuntapalvelut vastaa kuntoilupuistojen laitteista ja alueista, alueiden kunnossapidon hoitaa Teknisen Liikelaitoksen ylläpito-osasto. Ei talvikunnossapitoa.',
    infoLink: 'https://www.ouka.fi/oulu/liikunta-ja-ulkoilu/kuntoilupuistot',
    startDate: '2017-09-01',
    endDate: '2017-12-01',
  },
  {
    id: 6,
    name: 'Myllytulli',
    geometry: [
      65.014621,
      25.4838183,
    ],
    description: 'Myllytullissa sijaitsevan Puusepänpuiston laitteet sopivat parhaiten ikääntyneille. Puiston sijainti on Ainolan päiväkodin pohjoispuolella (Koulukatu 1, 90100 Oulu).<br /><br />Liikuntapalvelut vastaa kuntoilupuistojen laitteista ja alueista, alueiden kunnossapidon hoitaa Teknisen Liikelaitoksen ylläpito-osasto. Ei talvikunnossapitoa.',
    infoLink: 'https://www.ouka.fi/oulu/liikunta-ja-ulkoilu/kuntoilupuistot',
    startDate: '2017-09-01',
    endDate: '2017-12-01',
  },
  {
    id: 7,
    name: 'Raksila',
    geometry: [
      65.008619,
      25.5004514,
    ],
    description: 'Raksilan liikuntapuistossa sijaitseva kuntoilupuisto soveltuu ennen kaikkea aktiivikuntoilijoille. Kuntoilupuisto on Ouluhallin (Ylioppilaantie 4, 90100 Oulu) pohjoispuolella.<br /><br />Liikuntapalvelut vastaa kuntoilupuistojen laitteista ja alueista, alueiden kunnossapidon hoitaa Teknisen Liikelaitoksen ylläpito-osasto. Ei talvikunnossapitoa.',
    infoLink: 'https://www.ouka.fi/oulu/liikunta-ja-ulkoilu/kuntoilupuistot',
    startDate: '2017-09-01',
    endDate: '2017-12-01',
  },
  {
    id: 8,
    name: 'Kaukovainio',
    geometry: [
      64.994631,
      25.5145603,
    ],
    description: 'Vuonna 2015 rakennettiin kuntoilupuisto Kaukovainiolle Kainuunpuistoon Hiirosenkodin läheisyyteen (Merikotkantie 5, 90250 Oulu). Puiston laitteet on suunnattu ikäihmisille.<br /><br />Liikuntapalvelut vastaa kuntoilupuistojen laitteista ja alueista, alueiden kunnossapidon hoitaa Teknisen Liikelaitoksen ylläpito-osasto. Ei talvikunnossapitoa.',
    infoLink: 'https://www.ouka.fi/oulu/liikunta-ja-ulkoilu/kuntoilupuistot',
    startDate: '2017-09-01',
    endDate: '2017-12-01',
  },
  {
    id: 9,
    name: 'Pöllökangas',
    geometry: [
      65.067817,
      25.5132961,
    ],
    description: 'Liikuntapalvelut vastaa kuntoilupuistojen laitteista ja alueista, alueiden kunnossapidon hoitaa Teknisen Liikelaitoksen ylläpito-osasto. Ei talvikunnossapitoa.',
    infoLink: 'https://www.ouka.fi/oulu/liikunta-ja-ulkoilu/kuntoilupuistot',
    startDate: '2017-09-01',
    endDate: '2017-12-01',
  },
  {
    id: 10,
    name: 'Tinatien kenttä',
    geometry: [
      64.992594,
      25.5094933,
    ],
    description: 'Liikuntapalvelut vastaa kuntoilupuistojen laitteista ja alueista, alueiden kunnossapidon hoitaa Teknisen Liikelaitoksen ylläpito-osasto. Ei talvikunnossapitoa.',
    infoLink: 'https://www.ouka.fi/oulu/liikunta-ja-ulkoilu/kuntoilupuistot',
    startDate: '2017-09-01',
    endDate: '2017-12-01',
  },
  {
    id: 12,
    name: 'Sankivaara',
    geometry: [
      64.9815183,
      25.6914555,
    ],
    description: 'Liikuntapalvelut vastaa kuntoilupuistojen laitteista ja alueista, alueiden kunnossapidon hoitaa Teknisen Liikelaitoksen ylläpito-osasto. Ei talvikunnossapitoa.',
    infoLink: 'https://www.ouka.fi/oulu/liikunta-ja-ulkoilu/kuntoilupuistot',
    startDate: '2017-09-01',
    endDate: '2017-12-01',
  },
  {
    id: 13,
    name: 'Auran maja',
    geometry: [
      65.081576,
      25.5449617,
    ],
    description: 'Liikuntapalvelut vastaa kuntoilupuistojen laitteista ja alueista, alueiden kunnossapidon hoitaa Teknisen Liikelaitoksen ylläpito-osasto. Ei talvikunnossapitoa.',
    infoLink: 'https://www.ouka.fi/oulu/liikunta-ja-ulkoilu/kuntoilupuistot',
    startDate: '2017-09-01',
    endDate: '2017-12-01',
  },
  {
    id: 14,
    name: 'Honkimaa',
    geometry: [
      65.12053,
      25.7340172,
    ],
    description: 'Liikuntapalvelut vastaa kuntoilupuistojen laitteista ja alueista, alueiden kunnossapidon hoitaa Teknisen Liikelaitoksen ylläpito-osasto. Ei talvikunnossapitoa.',
    infoLink: 'https://www.ouka.fi/oulu/liikunta-ja-ulkoilu/kuntoilupuistot',
    startDate: '2017-09-01',
    endDate: '2017-12-01',
  },
  {
    id: 15,
    name: 'Tuokkosenmäki',
    geometry: [
      65.0890138,
      25.6923526,
    ],
    description: 'Liikuntapalvelut vastaa kuntoilupuistojen laitteista ja alueista, alueiden kunnossapidon hoitaa Teknisen Liikelaitoksen ylläpito-osasto. Ei talvikunnossapitoa.',
    infoLink: 'https://www.ouka.fi/oulu/liikunta-ja-ulkoilu/kuntoilupuistot',
    startDate: '2017-09-01',
    endDate: '2017-12-01',
  },
];
